#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Daimajia.Slider.Resource", IsApplication=false)]

namespace Daimajia.Slider
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001b
			public static int PagerIndicatorStyle = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public static int SliderStyle = 2130771994;
			
			// aapt resource value: 0x7f010001
			public static int auto_cycle = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int indicator_visibility = 2130771968;
			
			// aapt resource value: 0x7f010011
			public static int padding_bottom = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public static int padding_left = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public static int padding_right = 2130771983;
			
			// aapt resource value: 0x7f010010
			public static int padding_top = 2130771984;
			
			// aapt resource value: 0x7f010002
			public static int pager_animation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int pager_animation_span = 2130771971;
			
			// aapt resource value: 0x7f010006
			public static int selected_color = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int selected_drawable = 2130771976;
			
			// aapt resource value: 0x7f01000b
			public static int selected_height = 2130771979;
			
			// aapt resource value: 0x7f010015
			public static int selected_padding_bottom = 2130771989;
			
			// aapt resource value: 0x7f010012
			public static int selected_padding_left = 2130771986;
			
			// aapt resource value: 0x7f010013
			public static int selected_padding_right = 2130771987;
			
			// aapt resource value: 0x7f010014
			public static int selected_padding_top = 2130771988;
			
			// aapt resource value: 0x7f01000a
			public static int selected_width = 2130771978;
			
			// aapt resource value: 0x7f010005
			public static int shape = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int unselected_color = 2130771975;
			
			// aapt resource value: 0x7f010009
			public static int unselected_drawable = 2130771977;
			
			// aapt resource value: 0x7f01000d
			public static int unselected_height = 2130771981;
			
			// aapt resource value: 0x7f010019
			public static int unselected_padding_bottom = 2130771993;
			
			// aapt resource value: 0x7f010016
			public static int unselected_padding_left = 2130771990;
			
			// aapt resource value: 0x7f010017
			public static int unselected_padding_right = 2130771991;
			
			// aapt resource value: 0x7f010018
			public static int unselected_padding_top = 2130771992;
			
			// aapt resource value: 0x7f01000c
			public static int unselected_width = 2130771980;
			
			// aapt resource value: 0x7f010004
			public static int visibility = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int indicator_corner_bg = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public static int Accordion = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int Background2Foreground = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int CubeIn = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int Default = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int DepthPage = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int Fade = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int FlipHorizontal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public static int FlipPage = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public static int Foreground2Background = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public static int RotateDown = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public static int RotateUp = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public static int Stack = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public static int Tablet = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public static int ZoomIn = 2131099663;
			
			// aapt resource value: 0x7f060010
			public static int ZoomOut = 2131099664;
			
			// aapt resource value: 0x7f060011
			public static int ZoomOutSlide = 2131099665;
			
			// aapt resource value: 0x7f060014
			public static int daimajia_indicator_wrapper = 2131099668;
			
			// aapt resource value: 0x7f060015
			public static int daimajia_slider_image = 2131099669;
			
			// aapt resource value: 0x7f060019
			public static int daimajia_slider_viewpager = 2131099673;
			
			// aapt resource value: 0x7f06001c
			public static int default_bottom_left_indicator = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public static int default_bottom_right_indicator = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public static int default_center_bottom_indicator = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public static int default_center_top_indicator = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public static int default_center_top_left_indicator = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public static int default_center_top_right_indicator = 2131099678;
			
			// aapt resource value: 0x7f060018
			public static int description = 2131099672;
			
			// aapt resource value: 0x7f060017
			public static int description_layout = 2131099671;
			
			// aapt resource value: 0x7f060000
			public static int invisible = 2131099648;
			
			// aapt resource value: 0x7f060016
			public static int loading_bar = 2131099670;
			
			// aapt resource value: 0x7f060012
			public static int oval = 2131099666;
			
			// aapt resource value: 0x7f060013
			public static int rect = 2131099667;
			
			// aapt resource value: 0x7f060001
			public static int visible = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int indicator_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int render_type_default = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int render_type_text = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int slider_layout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public static int AndroidImageSlider_Attractive_Rect_Blue = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int AndroidImageSlider_Corner_Oval_Orange = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int AndroidImageSlider_Magnifier_Oval_Black = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PagerIndicator = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 13
			public static int PagerIndicator_padding_bottom = 13;
			
			// aapt resource value: 10
			public static int PagerIndicator_padding_left = 10;
			
			// aapt resource value: 11
			public static int PagerIndicator_padding_right = 11;
			
			// aapt resource value: 12
			public static int PagerIndicator_padding_top = 12;
			
			// aapt resource value: 2
			public static int PagerIndicator_selected_color = 2;
			
			// aapt resource value: 4
			public static int PagerIndicator_selected_drawable = 4;
			
			// aapt resource value: 7
			public static int PagerIndicator_selected_height = 7;
			
			// aapt resource value: 17
			public static int PagerIndicator_selected_padding_bottom = 17;
			
			// aapt resource value: 14
			public static int PagerIndicator_selected_padding_left = 14;
			
			// aapt resource value: 15
			public static int PagerIndicator_selected_padding_right = 15;
			
			// aapt resource value: 16
			public static int PagerIndicator_selected_padding_top = 16;
			
			// aapt resource value: 6
			public static int PagerIndicator_selected_width = 6;
			
			// aapt resource value: 1
			public static int PagerIndicator_shape = 1;
			
			// aapt resource value: 3
			public static int PagerIndicator_unselected_color = 3;
			
			// aapt resource value: 5
			public static int PagerIndicator_unselected_drawable = 5;
			
			// aapt resource value: 9
			public static int PagerIndicator_unselected_height = 9;
			
			// aapt resource value: 21
			public static int PagerIndicator_unselected_padding_bottom = 21;
			
			// aapt resource value: 18
			public static int PagerIndicator_unselected_padding_left = 18;
			
			// aapt resource value: 19
			public static int PagerIndicator_unselected_padding_right = 19;
			
			// aapt resource value: 20
			public static int PagerIndicator_unselected_padding_top = 20;
			
			// aapt resource value: 8
			public static int PagerIndicator_unselected_width = 8;
			
			// aapt resource value: 0
			public static int PagerIndicator_visibility = 0;
			
			public static int[] SliderLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public static int SliderLayout_auto_cycle = 1;
			
			// aapt resource value: 0
			public static int SliderLayout_indicator_visibility = 0;
			
			// aapt resource value: 2
			public static int SliderLayout_pager_animation = 2;
			
			// aapt resource value: 3
			public static int SliderLayout_pager_animation_span = 3;
			
			public static int[] Themes = new int[] {
					2130771994,
					2130771995};
			
			// aapt resource value: 1
			public static int Themes_PagerIndicatorStyle = 1;
			
			// aapt resource value: 0
			public static int Themes_SliderStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
